### ISSUE TITLE
Reporte-entrevista

### ISSUE THREAD

**Issue by ErikCuevas03** [SistemasTecTlaxiaco/actividad-2-entrevista-equipo-1-1#1]
[Reporte entrevista 2.pdf](https://github.com/user-attachments/files/16856877/Reporte.entrevista.2.pdf)

**Comment by Jaczibeth** [comment]
De acuerdo a la rubrica tienes el 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
